name: Github Actions Demo
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Github User"
      deploy:
        description: "Deploy the application?"
        required: false
        default: "yes"

jobs:
  Example-Action-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Print event name
        run: echo "The job is triggered by ${{ github.event_name }} event"

      - name: Print runner OS
        run: echo "The job is running on a ${{ runner.os }} runner"

      - name: Print repository details
        run: echo "The name of the branch is ${{ github.ref }} and your repository is ${{ github.repository }}"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Print workspace path
        run: echo "Repository copied to the path ${{ github.workspace }} on the runner"

      - name: Conditional step on pull request
        if: github.event_name == 'pull_request'
        run: echo "This step runs only if the event is a pull request"

      - name: List files in repository
        run: ls ${{ github.workspace }}

      - name: Setup .NET on runner
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"
      - name: Display .NET version
        run: dotnet --version

      - name: List preinstalled tools
        run: echo "The preinstalled tools are located in /opt/hostedtoolcache on the runner"

      - name: List tool cache directory
        run: ls /opt/hostedtoolcache

      - name: Print job status
        run: echo "The job status is ${{ job.status }}"
